In [1]:
import pandas as pd

df = pd.read_csv("purchase_order_dataset.csv")

df.head()

,PO_Number,PO_Date,Supplier,SKU,Ordered_Qty,Received_Qty,Unit_Cost,PO_Value,Expected_Delivery_Date,Actual_Delivery_Date,Lead_Time_Days,Fill_Rate,OTIF
0,PO00001,2025-01-13 00:00:00,Supplier_A,Sensor,809,798,2056,1663304,2025-01-20,2025-01-20,7,0.9864,1
1,PO00002,2025-02-22 00:00:00,Supplier_B,Belt,742,722,4887,3626154,2025-03-02,2025-03-02,8,0.9730,1
2,PO00003,2025-01-16 00:00:00,Supplier_A,Relay,145,142,1955,283475,2025-01-22,2025-01-22,6,0.9793,1
3,PO00004,2025-01-14 00:00:00,Supplier_E,Belt,624,570,4514,2816736,2025-02-04,2025-02-04,21,0.9135,1
4,PO00005,2025-08-18 00:00:00,Supplier_B,Pump,653,642,103,67259,2025-08-29,2025-08-29,11,0.9832,1

In [2]:
# Total Spend

df["PO_Value"].sum()

np.int64(1372515672)

In [3]:
# Supplier Spend

supplier_spend = (
    df.groupby("Supplier")["PO_Value"]
      .sum()
      .sort_values(ascending=False)
)

supplier_spend

Supplier
Supplier_C    327893060
Supplier_E    293727953
Supplier_D    255874823
Supplier_A    253914433
Supplier_B    241105403
Name: PO_Value, dtype: int64

In [4]:
# Supplier Performance

supplier_perf = (
    df.groupby("Supplier")
      .agg({
          "Fill_Rate":"mean",
          "OTIF":"mean",
          "Lead_Time_Days":"mean"
      })
)

supplier_perf

            Fill_Rate      OTIF  Lead_Time_Days
Supplier
Supplier_A   0.987977  0.989848        7.695431
Supplier_B   0.970090  0.924324       11.010811
Supplier_C   0.951460  0.876652       15.189427
Supplier_D   0.912512  0.842697       20.129213
Supplier_E   0.893228  0.751174       26.694836